scalar Id
scalar Text

type Category {
  id: Int!
  name: String
  about: Text
  parent: Int!
  topic_count: Int!
  category_count: Int!
  metadata_uri: String
}

type Topic {
  id: Int!
  title: String
  content: Text
  category: Category
  author: User
  pinned: Boolean
  parent: Int
  score: Float!
  reply_count: Int!
  vote_count: Int!
  metadata_uri: String
}

type TopicVote {
  id: String!
  voter: User
  topic: Topic
  choice: Int
}

type User {
  id: String!
  topic_count: Int!
  topic_vote_count: Int!
  profile: Profile
  statements: [Statement] @derivedFrom(field: "user")
}

type Profile {
  id: String!
  user: User!
  name: String
  about: Text
  twitter: String
  discord: String
  telegram: String
  github: String
  updated: Int
}

type Statement {
  id: String!
  user: User!
  org: String!
  statement: Text
  status: String
  updated: Int
}

type Vote { # rename to vote
  id: String!
  voter: String # User entity in sx-api
  space: String # Space entity in sx-api
  proposal: Int
  choice: Int
  vp: Float
  vp_raw: String # not part of sx-api
  created: Int
  chain_id: Int # not part of sx-api
  sig: Text # not part of sx-api
}
