scalar Id
scalar Text

type Category {
  id: String!
  category_id: Int!
  name: String
  about: Text
  parent: String!
  discussion_count: Int!
  category_count: Int!
  metadata_uri: String
}

type Discussion {
  id: String!
  discussion_id: Int
  title: String
  content: Text
  category: Category
  author: User
  parent: Int
  score: Float!
  reply_count: Int!
  vote_count: Int!
  metadata_uri: String
}

type Vote {
  id: String!
  voter: User
  discussion: Discussion
  choice: Int
}

type User {
  id: String!
  name: String
  about: Text
  discussion_count: Int!
  vote_count: Int!
}

type SXVote {
  id: String!
  space: String
  voter: String
  proposal_id: String
  choice: Int
  vp: Int
  chain_id: Int
  sig: Text
}
